environment_variables:
  OLLAMA_API_BASE: http://ollama:11434
general_settings:
  drop_params: false
model_list:
- litellm_params:
    api_base: http://ollama:11434
    model: ollama/hf.co/elyza/Llama-3-ELYZA-JP-8B-GGUF:latest
  model_name: elyza
- litellm_params:
    model: openai/gpt-4o-mini
  model_name: gpt-4o-mini
- litellm_params:
    model: openai/gpt-4o
  model_name: gpt-4o
