version: '3'

services:
  # Ollamaサービス - ローカルLLMモデルを実行（CPU版）
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  # LiteLLM Proxyサービス - 統一インターフェースを提供
  litellm:
    build:
      context: ./litellm_proxy
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: litellm
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
      - PORT=8000
      - HOST=0.0.0.0
    volumes:
      - ./litellm_proxy/config.yaml:/app/config.yaml
    restart: unless-stopped

  # APIサービス - モデルダウンロード・管理
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: llm-bridge-api
    ports:
      - "9999:9999"
    depends_on:
      - ollama
      - litellm
    volumes:
      - .:/app                              # アプリケーションコード
      - ollama_data:/root/.ollama:ro        # モデルキャッシュを読み取り専用で共有
      - /var/run/docker.sock:/var/run/docker.sock  # ← docker CLI利用用
    restart: unless-stopped

volumes:
  ollama_data:
